package com.natehardison.simplejson.domain;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Model class for a simple Person entity.
 * @author Nate Hardison <natehardison@gmail.com>
 */
@XmlRootElement
public class Person {

    // this ID will be auto-generated by the database.
    protected long id;
    protected String name;
    protected int age;

    // empty constructor needed for Hibernate
    public Person() {}

    public long getId() { return this.id; }
    public void setId(long id) { this.id = id; }

    public String getName() { return this.name; }
    public void setName(String name) { this.name = name; }

    public int getAge() { return this.age; }
    public void setAge(int age) { this.age = age; }

}
